using CareerCopilot.Models;

namespace CareerCopilot.Services;

/// <summary>
/// Stub — returns the advice already generated by FitAnalyzerOpenAI.
/// For a richer implementation, make a separate LLM call here.
/// </summary>
public class ResumeOptimizerStub : IResumeOptimizer
{
    public Task<ResumeAdvice> GetAdviceAsync(Job job, UserProfile profile, CancellationToken ct = default)
    {
        var advice = new ResumeAdvice(
            Summary: "Review the job description and move the most relevant skills to the top of your skills section.",
            HighlightSkills: profile.Skills.Split(',').Take(3).Select(s => s.Trim()).ToList(),
            HighlightBullets: ["Most relevant project or achievement goes here."]
        );
        return Task.FromResult(advice);
    }
}
